spring.application.name=springsecOAUTH2
spring.security.user.name=${SECURITY_USERNAME:eazybytes}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liXdtJ9bNcI9l5x9}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:f8b6768a847049103424e4c49c060a124a8c75eb}

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:1325770972705416}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:df31ee7d87ad8f7926bbfb17e47ad709}